name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.37
      - name: Run gosec
        run: |
          go get github.com/securego/gosec/v2/cmd/gosec
          gosec ./...

  test:
    name: Test
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run test
        run: go test ./...

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Generate coverage
        run: go test ./... -cover -coverprofile coverage.out -covermode atomic
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.out
