name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  go-versions:
    name: Fetch Go versions
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.versions.outputs.value }}
    steps:
      - name: Fetch versions
        id: versions
        run: |
          versions=$(curl -s 'https://go.dev/dl/?mode=json' | jq -c 'ma(.version[2:])')
          echo "::set-output name=value::${versions}"

  lint:
    name: Lint
    needs:
      - go-versions
    stratgy:
      matrix:
        go-version: ${{ fromJson(needs.go-versions.outputs.versions) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49
      - name: Run gosec
        run: go run github.com/securego/gosec/v2/cmd/gosec@latest ./...
      - name: Run govulncheck
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...

  test:
    name: Test
    strategy:
      matrix:
        go-version: ${{ fromJson(needs.go-versions.outputs.versions) }}
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run test
        run: go test ./...

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: Generate coverage
        run: go test ./... -cover -coverprofile coverage.out -covermode atomic
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.out
